# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too

aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2.1
jobs:
  deploy-website:
    docker:
      # specify the version of Node you desire here
      - image: circleci/node:buster
    resource_class: 2xlarge

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake curl clang
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
            echo 'export PATH="$PATH:$HOME/.cargo/bin"' >> $BASH_ENV
      - run:
          name: Deploying Libra Website to GitHub Pages
          command: |
            git config --global user.email "libra-doc-bot@users.noreply.github.com"
            git config --global user.name "Libra Website Deployment Script"
            echo "machine github.com login libra-doc-bot password $PUBLISH_WEBSITE_TOKEN" > ~/.netrc
            ./scripts/build_docs.sh -b -r
            cd website
            GIT_USER=libra-doc-bot USE_SSH=false yarn run publish-gh-pages

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master
